// Generated by npm run gen:c-headers. Do not edit.
#ifndef JSCPU_OS_GUEST_CONFIG_H
#define JSCPU_OS_GUEST_CONFIG_H

#define CFG_ARGBUF_LEN 512
#define CFG_BOOT_MAGIC 0x544f4f42
#define CFG_BUF_DATA_LEN 0x2000
#define CFG_CLOCK_MONOTONIC 1
#define CFG_CLOCK_REALTIME 0
#define CFG_CONSOLE_DATA 1016
#define CFG_DINODE_SIZE 80
#define CFG_DIRSIZ 14
#define CFG_DISK_DATA 496
#define CFG_DISK_POS 498
#define CFG_E2BIG 7
#define CFG_EACCES 13
#define CFG_EBADF 9
#define CFG_ECHILD 10
#define CFG_EEXIST 17
#define CFG_EFAULT 14
#define CFG_EFBIG 27
#define CFG_EINTR 4
#define CFG_EINVAL 22
#define CFG_EISDIR 21
#define CFG_ELOOP 40
#define CFG_EMFILE 24
#define CFG_EMLINK 31
#define CFG_ENAMETOOLONG 36
#define CFG_ENFILE 23
#define CFG_ENODEV 19
#define CFG_ENOENT 2
#define CFG_ENOEXEC 8
#define CFG_ENOMEM 12
#define CFG_ENOSPC 28
#define CFG_ENOSYS 38
#define CFG_ENOTDIR 20
#define CFG_ENOTEMPTY 39
#define CFG_ENOTTY 25
#define CFG_EPERM 1
#define CFG_EPIPE 32
#define CFG_EROFS 30
#define CFG_ESPIPE 29
#define CFG_ESRCH 3
#define CFG_EXEC_MAGIC 0x35315850
#define CFG_F_DUPFD 0
#define CFG_F_GETFD 1
#define CFG_F_GETFL 3
#define CFG_F_SETFD 2
#define CFG_F_SETFL 4
#define CFG_FD_CLOEXEC 1
#define CFG_FLAG_IF 8
#define CFG_FRAME_POOL_BASE 0x100000
#define CFG_FRAME_POOL_END 0x380000
#define CFG_FS_MAGIC 0x10203040
#define CFG_FS_VERSION 2
#define CFG_FT_CONS 1
#define CFG_FT_FILE 3
#define CFG_FT_KBD 2
#define CFG_FT_NONE 0
#define CFG_FT_PIPE 4
#define CFG_IDT 0x40000
#define CFG_IDT_ENTRY_SIZE 8
#define CFG_IDT_PRESENT 1
#define CFG_IDT_USER 2
#define CFG_INITPATH_LEN 64
#define CFG_IPB 6
#define CFG_KBD_DATA 96
#define CFG_KBD_STATUS 100
#define CFG_KBD_VECTOR 33
#define CFG_KERNEL_PT 0x41000
#define CFG_KSTACK_TOP 0x50000
#define CFG_MAP_ANONYMOUS 32
#define CFG_MAP_FIXED 16
#define CFG_MAP_PRIVATE 2
#define CFG_MAP_SHARED 1
#define CFG_MAX_PROC 8
#define CFG_MAX_VMAS 16
#define CFG_MAXARG 16
#define CFG_MAXFILE 140
#define CFG_MODE_USER 1
#define CFG_NBUF 16
#define CFG_NDIRECT 12
#define CFG_NFD 16
#define CFG_NFILE 128
#define CFG_NINDIRECT 128
#define CFG_NPIPE 8
#define CFG_NSIG 32
#define CFG_NSYS 51
#define CFG_O_ACCMODE 3
#define CFG_O_CREATE 512
#define CFG_O_NONBLOCK 2048
#define CFG_O_RDWR 2
#define CFG_O_TRUNC 1024
#define CFG_O_WRONLY 1
#define CFG_PAGEFAULT_VECTOR 14
#define CFG_PIPESZ 512
#define CFG_POWER 1540
#define CFG_POWER_OFF 0x2000
#define CFG_PROT_EXEC 4
#define CFG_PROT_NONE 0
#define CFG_PROT_READ 1
#define CFG_PROT_WRITE 2
#define CFG_PTE_KERNEL 3
#define CFG_PTE_USER 7
#define CFG_ROOTINO 1
#define CFG_RTC_DATA 112
#define CFG_S_IFDIR 0x4000
#define CFG_S_IFLNK 0xa000
#define CFG_S_IFMT 0xf000
#define CFG_S_IFREG 0x8000
#define CFG_SEEK_CUR 1
#define CFG_SEEK_END 2
#define CFG_SEEK_SET 0
#define CFG_SIG_BLOCK 0
#define CFG_SIG_DFL 0
#define CFG_SIG_IGN 1
#define CFG_SIG_SETMASK 2
#define CFG_SIG_UNBLOCK 1
#define CFG_SIGCHLD 17
#define CFG_SIGCONT 18
#define CFG_SIGHUP 1
#define CFG_SIGINT 2
#define CFG_SIGKILL 9
#define CFG_SIGSEGV 11
#define CFG_SIGSTOP 19
#define CFG_SIGTERM 15
#define CFG_SIGTSTP 20
#define CFG_SIGUSR1 10
#define CFG_ST_RUNNABLE 1
#define CFG_ST_SLEEPING 3
#define CFG_ST_STOPPED 4
#define CFG_ST_UNUSED 0
#define CFG_ST_ZOMBIE 2
#define CFG_SYS_BRK 26
#define CFG_SYS_CHMOD 39
#define CFG_SYS_CHOWN 40
#define CFG_SYS_CLOCK_GETTIME 33
#define CFG_SYS_CLOSE 8
#define CFG_SYS_DUP 11
#define CFG_SYS_EXEC 5
#define CFG_SYS_EXIT 0
#define CFG_SYS_FCNTL 30
#define CFG_SYS_FORK 4
#define CFG_SYS_FSTAT 37
#define CFG_SYS_GETDENTS 35
#define CFG_SYS_GETGID 50
#define CFG_SYS_GETPID 3
#define CFG_SYS_GETPPID 24
#define CFG_SYS_GETTIMEOFDAY 32
#define CFG_SYS_GETUID 49
#define CFG_SYS_IOCTL 31
#define CFG_SYS_KILL 15
#define CFG_SYS_LINK 44
#define CFG_SYS_LSEEK 48
#define CFG_SYS_LSTAT 38
#define CFG_SYS_MKDIR 41
#define CFG_SYS_MMAP 27
#define CFG_SYS_MPROTECT 29
#define CFG_SYS_MUNMAP 28
#define CFG_SYS_NANOSLEEP 25
#define CFG_SYS_OPEN 7
#define CFG_SYS_PIPE 10
#define CFG_SYS_READ 9
#define CFG_SYS_READLINK 47
#define CFG_SYS_RENAME 45
#define CFG_SYS_RMDIR 42
#define CFG_SYS_SETPGID 20
#define CFG_SYS_SETSID 21
#define CFG_SYS_SHUTDOWN 14
#define CFG_SYS_SIGACTION 16
#define CFG_SYS_SIGPROCMASK 17
#define CFG_SYS_SIGRETURN 18
#define CFG_SYS_STAT 36
#define CFG_SYS_SYMLINK 46
#define CFG_SYS_TCGETPGRP 23
#define CFG_SYS_TCSETPGRP 22
#define CFG_SYS_TIME 13
#define CFG_SYS_UNAME 34
#define CFG_SYS_UNLINK 43
#define CFG_SYS_UPTIME 12
#define CFG_SYS_WAIT 6
#define CFG_SYS_WAITPID 19
#define CFG_SYS_WRITE 1
#define CFG_SYS_YIELD 2
#define CFG_SYSCALL_INSTR_SIZE 5
#define CFG_SYSCALL_VECTOR 128
#define CFG_T_DIR 1
#define CFG_T_FILE 2
#define CFG_T_SYMLINK 3
#define CFG_TICKS_PER_SEC 100
#define CFG_TIMER_PERIOD 0x1f40
#define CFG_TIMER_VECTOR 32
#define CFG_TIOCGPGRP 0x540f
#define CFG_TIOCSPGRP 0x5410
#define CFG_USER_BASE 0x400000
#define CFG_USER_END 0x800000
#define CFG_USER_LOAD_BASE 0x400000
#define CFG_USER_STACK_PAGE 0x7ff000
#define CFG_USER_STACK_TOP 0x800000
#define CFG_WCONTINUED 4
#define CFG_WNOHANG 1
#define CFG_WUNTRACED 2

// Intrinsics recognized by src/toolchain/c.ts.
int __syscall(int number, int arg1, int arg2, int arg3);
int __out(int port, int value);
int __in(int port);
int __halt(void);
int __iret(void);
int __lidt(int address);
int __lksp(int address);
int __stmr(int period);
int __lptbr(int address);
int __pgon(void);
int __pgoff(void);
int __rdpfla(void);
int __rderr(void);
int __ei(void);
int __di(void);

// Guest libc errno: a negative syscall return becomes errno + a -1 result.
extern int errno;

// Freestanding runtime and guest libc functions.
void *memcpy(void *destination, const void *source, int length);
void *memset(void *destination, int value, int length);
int strlen(const char *text);
int strcmp(const char *left, const char *right);
int write(int fd, char *buffer, int length);
int read(int fd, char *buffer, int length);
int open(char *path, int flags);
int close(int fd);
int fork(void);
int wait(void);
int waitpid(int pid, int *status, int options);
int exec(char *path, char **argv);
int getpid(void);
int getppid(void);
int kill(int pid, int signal);
typedef void (*sighandler_t)(int signal);
struct sigaction {
  sighandler_t handler;
  int mask;
  int flags;
  int restorer;
};
int signal(int signal, sighandler_t handler);
int sigaction(int signal, struct sigaction *action, struct sigaction *old_action);
int sigprocmask(int how, int mask, int *old_mask);
int setpgid(int pid, int pgid);
int setsid(void);
int tcsetpgrp(int pgid);
int tcgetpgrp(void);
int pipe(int *fds);
int dup(int fd);
int fcntl(int fd, int command, int argument);
int ioctl(int fd, int request, int argument);
struct timespec {
  int tv_sec;
  int tv_nsec;
};
struct timeval {
  int tv_sec;
  int tv_usec;
};
struct mmap_args {
  int address;
  int length;
  int protection;
  int flags;
  int fd;
  int offset;
};
struct utsname {
  char sysname[32];
  char nodename[32];
  char release[32];
  char version[32];
  char machine[32];
  char domainname[32];
};
struct dirent {
  int ino;
  int offset;
  int reclen;
  int type;
  char name[16];
};
struct stat {
  int dev;
  int ino;
  int mode;
  int nlink;
  int uid;
  int gid;
  int rdev;
  int size;
  int blksize;
  int blocks;
  int atime;
  int mtime;
  int ctime;
};
int nanosleep(struct timespec *request, struct timespec *remaining);
int brk(void *address);
void *sbrk(int increment);
void *mmap(void *address, int length, int protection, int flags, int fd, int offset);
int munmap(void *address, int length);
int mprotect(void *address, int length, int protection);
int gettimeofday(struct timeval *value, void *timezone);
int clock_gettime(int clock_id, struct timespec *value);
int uname(struct utsname *name);
int getdents(int fd, struct dirent *entries, int count);
int stat(char *path, struct stat *value);
int fstat(int fd, struct stat *value);
int lstat(char *path, struct stat *value);
int chmod(char *path, int mode);
int chown(char *path, int uid, int gid);
int mkdir(char *path, int mode);
int rmdir(char *path);
int unlink(char *path);
int link(char *oldpath, char *newpath);
int rename(char *oldpath, char *newpath);
int symlink(char *target, char *linkpath);
int readlink(char *path, char *buffer, int size);
int lseek(int fd, int offset, int whence);
int getuid(void);
int getgid(void);
void exit(int code);
int time(void);
void shutdown(void);

#endif
