// Generated by npm run gen:c-headers. Do not edit.
#ifndef JSCPU_OS_GUEST_CONFIG_H
#define JSCPU_OS_GUEST_CONFIG_H

#define CFG_ARGBUF_LEN 512
#define CFG_BOOT_MAGIC 0x544f4f42
#define CFG_BUF_DATA_LEN 0x2000
#define CFG_CONSOLE_DATA 1016
#define CFG_DINODE_SIZE 64
#define CFG_DIRSIZ 14
#define CFG_DISK_DATA 496
#define CFG_DISK_POS 498
#define CFG_E2BIG 7
#define CFG_EBADF 9
#define CFG_ECHILD 10
#define CFG_EFAULT 14
#define CFG_EINVAL 22
#define CFG_EMFILE 24
#define CFG_ENFILE 23
#define CFG_ENOENT 2
#define CFG_ENOEXEC 8
#define CFG_ENOMEM 12
#define CFG_ENOSYS 38
#define CFG_EPERM 1
#define CFG_EPIPE 32
#define CFG_ESRCH 3
#define CFG_EXEC_MAGIC 0x35315850
#define CFG_FLAG_IF 8
#define CFG_FRAME_POOL_BASE 0x100000
#define CFG_FRAME_POOL_END 0x380000
#define CFG_FS_MAGIC 0x10203040
#define CFG_FT_CONS 1
#define CFG_FT_FILE 3
#define CFG_FT_KBD 2
#define CFG_FT_NONE 0
#define CFG_FT_PIPE 4
#define CFG_IDT 0x40000
#define CFG_IDT_ENTRY_SIZE 8
#define CFG_IDT_PRESENT 1
#define CFG_IDT_USER 2
#define CFG_INITPATH_LEN 64
#define CFG_IPB 8
#define CFG_KBD_DATA 96
#define CFG_KBD_STATUS 100
#define CFG_KBD_VECTOR 33
#define CFG_KERNEL_PT 0x41000
#define CFG_KSTACK_TOP 0x50000
#define CFG_MAX_PROC 8
#define CFG_MAXARG 16
#define CFG_MODE_USER 1
#define CFG_NBUF 16
#define CFG_NDIRECT 12
#define CFG_NFD 16
#define CFG_NPIPE 8
#define CFG_NSYS 15
#define CFG_PAGEFAULT_VECTOR 14
#define CFG_PIPESZ 512
#define CFG_POWER 1540
#define CFG_POWER_OFF 0x2000
#define CFG_PTE_KERNEL 3
#define CFG_PTE_USER 7
#define CFG_ROOTINO 1
#define CFG_RTC_DATA 112
#define CFG_ST_RUNNABLE 1
#define CFG_ST_SLEEPING 3
#define CFG_ST_UNUSED 0
#define CFG_ST_ZOMBIE 2
#define CFG_SYS_CLOSE 8
#define CFG_SYS_DUP 11
#define CFG_SYS_EXEC 5
#define CFG_SYS_EXIT 0
#define CFG_SYS_FORK 4
#define CFG_SYS_GETPID 3
#define CFG_SYS_OPEN 7
#define CFG_SYS_PIPE 10
#define CFG_SYS_READ 9
#define CFG_SYS_SHUTDOWN 14
#define CFG_SYS_TIME 13
#define CFG_SYS_WAIT 6
#define CFG_SYS_WRITE 1
#define CFG_SYS_YIELD 2
#define CFG_SYSCALL_INSTR_SIZE 5
#define CFG_SYSCALL_VECTOR 128
#define CFG_T_DIR 1
#define CFG_T_FILE 2
#define CFG_TIMER_PERIOD 0x1f40
#define CFG_TIMER_VECTOR 32
#define CFG_USER_BASE 0x400000
#define CFG_USER_END 0x800000
#define CFG_USER_LOAD_BASE 0x400000
#define CFG_USER_STACK_PAGE 0x7ff000
#define CFG_USER_STACK_TOP 0x800000

// Intrinsics recognized by src/toolchain/c.ts.
int __syscall(int number, int arg1, int arg2, int arg3);
int __out(int port, int value);
int __in(int port);
int __halt(void);
int __iret(void);
int __lidt(int address);
int __lksp(int address);
int __stmr(int period);
int __lptbr(int address);
int __pgon(void);
int __pgoff(void);
int __rdpfla(void);
int __rderr(void);
int __ei(void);
int __di(void);

// Guest libc errno: a negative syscall return becomes errno + a -1 result.
extern int errno;

// Freestanding runtime and guest libc functions.
void *memcpy(void *destination, const void *source, int length);
void *memset(void *destination, int value, int length);
int strlen(const char *text);
int strcmp(const char *left, const char *right);
int write(int fd, char *buffer, int length);
int read(int fd, char *buffer, int length);
int open(char *path, int flags);
int close(int fd);
int fork(void);
int wait(void);
int exec(char *path, char **argv);
int getpid(void);
int pipe(int *fds);
int dup(int fd);
void exit(int code);
int time(void);
void shutdown(void);

#endif
