#ifndef JSCPU_OS_ERRNO_H
#define JSCPU_OS_ERRNO_H

extern int errno;

#define EPERM CFG_EPERM
#define ENOENT CFG_ENOENT
#define ESRCH CFG_ESRCH
#define EINTR CFG_EINTR
#define E2BIG CFG_E2BIG
#define ENOEXEC CFG_ENOEXEC
#define EBADF CFG_EBADF
#define ECHILD CFG_ECHILD
#define EAGAIN CFG_EAGAIN
#define ENOMEM CFG_ENOMEM
#define EACCES CFG_EACCES
#define EFAULT CFG_EFAULT
#define EEXIST CFG_EEXIST
#define ENODEV CFG_ENODEV
#define ENOTDIR CFG_ENOTDIR
#define EISDIR CFG_EISDIR
#define EINVAL CFG_EINVAL
#define ENFILE CFG_ENFILE
#define EMFILE CFG_EMFILE
#define EFBIG CFG_EFBIG
#define ENOSPC CFG_ENOSPC
#define ESPIPE CFG_ESPIPE
#define EROFS CFG_EROFS
#define EMLINK CFG_EMLINK
#define EPIPE CFG_EPIPE
#define ENAMETOOLONG CFG_ENAMETOOLONG
#define ENOSYS CFG_ENOSYS
#define ENOTEMPTY CFG_ENOTEMPTY
#define ELOOP CFG_ELOOP
#define EMSGSIZE CFG_EMSGSIZE
#define EOPNOTSUPP CFG_EOPNOTSUPP

#endif
